Gear inches
VodolazUA/bicycle pull request #3
Opened 2024-01-10 17:48 UTC by VodolazUA

a task regarding `gear inches`. 
new classes Wheel, Bicycle
new testing case

2024-01-10 18:16 UTC, maestro5 commented on app.py
> +bike1.setup_wheel("r", 27, 0.5)
якщо ти хочеш збирати велосипед, то так і роби
`bike1 = Bicycle(front_wheel: Wheel(27, 0.5), gear: Gear(52, 11))`

2024-01-10 18:16 UTC, maestro5 commented on app.py
> +bike1.setup_wheel("r", 27, 0.5)
трохи бідовий велосипед, з колесом і передачами

2024-01-10 18:16 UTC, maestro5 commented on app.py
> +bike1.setup_wheel("r", 27, 0.5)
це якщо деталей велосипеда буде багато, то для того щоб порахувати gear_inches мені потрібно буде зібрати увесь велосипед?

2024-01-10 18:16 UTC, maestro5 commented on app.py
> +            self.rear_wheel = Wheel(rim_diameter, tire_height)
використовуй ООП

2024-01-10 22:38 UTC, VodolazUA commented on app.py
> +bike1.setup_wheel("r", 27, 0.5)
> якщо ти хочеш збирати велосипед, то так і роби `bike1 = Bicycle(front_wheel: Wheel(27, 0.5), gear: Gear(52, 11))`

Якщо так робити, тоді при збільшенні запчастин=обʼєктів у велосипеді процес створення нового обʼєкту буде виглядати дуже громоздко, та, мабуть, не читабєльно. Тому вирішив ініціалізацію вузлів велосипеда винисти в окремі методи.

2024-01-10 22:39 UTC, VodolazUA commented on app.py
> +bike1.setup_wheel("r", 27, 0.5)
> трохи бідовий велосипед, з колесом і передачами

то ж модульний велосипед, кастомний - збирай його з чого бажається

2024-01-10 22:44 UTC, VodolazUA commented on app.py
> +bike1.setup_wheel("r", 27, 0.5)
> це якщо деталей велосипеда буде багато, то для того щоб порахувати gear_inches мені потрібно буде зібрати увесь велосипед?

Ні. Я ж спеціально виніс ініціалізацію вузлів в окремі методи. Для підрахунку `gear_inches` потрібно лише дві запчастини=вузли=обʼєкти, а саме - 1) `gear` та 2) `rear_wheel`.

2024-01-10 23:34 UTC, VodolazUA commented on app.py
> +            self.rear_wheel = Wheel(rim_diameter, tire_height)
> використовуй ООП

використав

2024-01-11 11:30 UTC, maestro5 requested changes

2024-01-11 11:30 UTC, maestro5 commented on app.py
> +        if front_wheel is not None:
для чого цей `if`?

2024-01-11 11:30 UTC, maestro5 commented on app.py
> +        if rear_wheel is not None:
для чого цей `if`?

2024-01-11 11:30 UTC, maestro5 commented on app.py
> +bike1 = Bicycle()
чи легко твоїм колегам, а через деякий час і тобі, користуватись цим касом Bicycle()? От я хочу використати цей клас, я очікую, що `my_super_bike = Bicycle()` створить об"єкт класу Bicycle, об"єкт готовий до роботи, але отримаю якийсь пустий велосипед і як наслідок, нічого працювати не буде (

2024-01-11 11:30 UTC, maestro5 commented on app.py
> +    bike1.gear_inches()
даний метод в тебе працює бо ти перехоплюєш помилки, але залежності які ти заклав вимагають додаткової перевірки перед використанням даного методу, тобто перед тим як його викликати потрібно ще перевірити чи встановлені колеса і чи встановлені передачі

2024-01-11 22:40 UTC, VodolazUA commented on app.py
> +        if front_wheel is not None:
> для чого цей `if`?

в цей метод можна передати будь-яке одне колесо. цей 'if' дивиться, чи колесо передано як параметр чи ні

2024-01-11 22:40 UTC, VodolazUA commented on app.py
> +        if rear_wheel is not None:
> для чого цей `if`?

в цей метод можна передати будь-яке одне колесо. цей 'if' дивиться, чи колесо передано як параметр чи ні

2024-01-11 22:53 UTC, VodolazUA commented on app.py
> +bike1 = Bicycle()
> чи легко твоїм колегам, а через деякий час і тобі, користуватись цим касом Bicycle()? От я хочу використати цей клас, я очікую, що `my_super_bike = Bicycle()` створить об"єкт класу Bicycle, об"єкт готовий до роботи, але отримаю якийсь пустий велосипед і як наслідок, нічого працювати не буде (

А ти уяви, якщо зробити як ти говорит - при створенні обʼєкту він має бути НЕ пустуий, тобно при створенні веліку необхідно одразу вказувати всі параметри - це ж буде дуже громоздко.

2024-01-11 22:54 UTC, VodolazUA commented on app.py
> +    bike1.gear_inches()
> даний метод в тебе працює бо ти перехоплюєш помилки, але залежності які ти заклав вимагають додаткової перевірки перед використанням даного методу, тобто перед тим як його викликати потрібно ще перевірити чи встановлені колеса і чи встановлені передачі

воно буде працювати навіть якщо вєл буде "пустим", просто метод поверне 0. Не бачу сенсу в додаткових перевірках

2024-01-12 10:30 UTC, maestro5 commented on app.py
> +        if front_wheel is not None:
якщо `front_wheel` переданий як параметр, то `self.front_wheel = front_wheel`, якщо не переданий, то `front_wheel #-> None` і `self.front_wheel #-> None` тобто `None = None`, тобто `self.front_wheel = front_wheel` ні? То для чого ці `if`?

2024-01-12 10:31 UTC, maestro5 commented on app.py
> +        if front_wheel is not None:
```
def setup_wheels(self, front_wheel=None, rear_wheel=None):
    self.front_wheel = front_wheel
    self.rear_wheel = rear_wheel
```

2024-01-12 10:33 UTC, maestro5 commented on app.py
> +    bike1.gear_inches()
так, не очевидна поведінка

2024-01-12 10:34 UTC, maestro5 requested changes

2024-01-12 10:34 UTC, maestro5 commented on app.py
> +
який обов"язок ти закладаєш в клас Bicycle, за що він відповідає?

2024-01-12 16:04 UTC, VodolazUA commented on app.py
> +        if front_wheel is not None:
> якщо `front_wheel` переданий як параметр, то `self.front_wheel = front_wheel`, якщо не переданий, то `front_wheel #-> None` і `self.front_wheel #-> None` тобто `None = None`, тобто `self.front_wheel = front_wheel` ні? То для чого ці `if`?

Блін, ти правий. Я - благородний олень.

2024-01-12 16:06 UTC, VodolazUA commented on app.py
> +    bike1.gear_inches()
> так, не очевидна поведінка

ок. як би ти зробив?

2024-01-12 16:07 UTC, VodolazUA commented on app.py
> +
> який обов"язок ти закладаєш в клас Bicycle, за що він відповідає?

каркас=конструктор, на який вішаютья необхідні модулі=запчастини

2024-01-12 16:24 UTC, maestro5 commented on app.py
> +
Наразі я бачу дві відповідальності 1) збирати велосипеди, в такому разі варто було б назву підправити; 2) бути велосипедом, поводитись як велосипед - розраховує gear_inches. Має бути одна відповідальність. 

Будь ласка, почитай, ці задачки були якраз на ось це
https://towardsdatascience.com/single-responsibility-principle-in-python-ac4178b922de
https://realpython.com/solid-principles-python/

і виправи

2024-01-12 16:27 UTC, maestro5 commented on app.py
> +
класи як і окремі методи повинні мати одну відповідальність

2024-01-12 16:28 UTC, maestro5 commented on app.py
> +    bike1.gear_inches()
проблема відпаде коли ти розділиш відповідальнітсь Bicycle

2024-01-12 16:29 UTC, maestro5 commented on app.py
> +    bike1.gear_inches()
Переглянь ще раз про перехоплення помилок, можливо ти не так щось зрозумів? Скинь я почитаю.

2024-01-12 23:00 UTC, VodolazUA commented on app.py
> +
відрефакторив, запушив сюди

2024-01-12 23:01 UTC, VodolazUA commented on app.py
> +    bike1.gear_inches()
відрефакторив, запушив

2024-01-13 09:43 UTC, maestro5 commented on app.py
> +    gear=Gear(52, 11)
я думав ти додасиш якийсь новий клас, типу BicycleConstructor чи BicycleCreator, щось таке

2024-01-13 09:43 UTC, maestro5 commented on app.py
> +    gear=Gear(52, 11)
ти так зробив бо розібрався, чи того що я тебе дістав?

2024-01-13 09:51 UTC, maestro5 commented on app.py
> +    bike1.gear_inches()
> > так, не очевидна поведінка
> 
> ок. як би ти зробив?

спочатку я би додав в той клас що у мене вже був

```
class Gear:

    def __init__(self, chainring: int, cog: int, rim: int, tire: int):
        self.chainring = chainring
        self.cog = cog
        self.rim = rim
        self.tire = tire

    def ratio(self) -> float:
        round(self.chainring / self.cog, 2)

    def gear_inches
      ratio() * (self.rim + (self.tire * 2))
```

Потім зрозумів би що діаметр колеса - це щось не з відси і відділив би його

2024-01-14 01:27 UTC, VodolazUA commented on app.py
> +    gear=Gear(52, 11)
Я так зробив, після того як прочитав статтю з `medium`. В принципі це досить логічно та очевидно. Не знаю наскільки такий підхід буде зручний в реальному житті, але раз ти за нього топиш, то мабуть воно має сенс.

2024-01-14 01:34 UTC, VodolazUA commented on app.py
> +    bike1.gear_inches()
`
class Gear:
  def __init__(self, chainring: int, cog: int, diameter=none):
      self.chainring = chainring
      self.cog = cog
      self.diameter = diameter
...
`
як на мене, то не логічно передавати в клас Gear діаметр колеса (`diameter`) - це властивість яка ніяк напряму не повʼязана з `Gear`.

2024-01-14 01:38 UTC, VodolazUA commented on app.py
> +    bike1.gear_inches()
Той код, який на зараз є актуальним -  що з ним не так?

2024-01-14 08:44 UTC, maestro5 approved these changes

2024-01-14 16:14 UTC, merged