circumference of a wheel
VodolazUA/bicycle pull request #4
Opened 2024-01-17 15:57 UTC by VodolazUA

added a method <circumference> to the calss Bicycle; testing data updated

2024-01-17 16:42 UTC, maestro5 requested changes

2024-01-17 16:42 UTC, maestro5 commented on app.py
> +        return wheel.wheel_diameter * 3.1415
використовуй константу
```
# Import math Library
import math

# Print the value of pi
print (math.pi)
```

2024-01-17 16:42 UTC, maestro5 commented on app.py
> +    bike1.circumference(bike1.front_wheel)
нічого не смущає?

2024-01-18 02:39 UTC, VodolazUA commented on app.py
> +        return wheel.wheel_diameter * 3.1415
Без проблем - я спеціально ни використовував, наче у нас окрім Пі ніякий функцій з бібліотеки math не планується використовувати, тому і не хотів її (бібліотеку) імпортувати. Але якщо бос каже юзати, то будемо юзати.

2024-01-18 02:44 UTC, VodolazUA commented on app.py
> +    bike1.circumference(bike1.front_wheel)
> нічого не смущає?

ну як методу колесо передати як аргумент по іншому? у вєла є як мінімум два колеса, а може потім буде вєл в якого буде 3 колеса і нам потрібно розуміти для якого колеса обичлити окружність. 

або ще варіант перенести цей метод зі класу Bicycle в клас Wheel. особисто мені так цей варіант більше подобаєтья. 

Але ти кажи що не так.

2024-01-18 08:07 UTC, maestro5 commented on app.py
> +        return wheel.wheel_diameter * 3.1415
Погоджуюсь, для бібліотеки замало, але цифра мала бути в константі

2024-01-18 08:09 UTC, maestro5 commented on app.py
> +    bike1.circumference(bike1.front_wheel)
Не зрозумів який варіант більше подобається, додай будь ласка більше контексту, поділись своїм ходом думок

2024-01-18 15:33 UTC, VodolazUA commented on app.py
> +    bike1.circumference(bike1.front_wheel)
> Не зрозумів який варіант більше подобається, додай будь ласка більше контексту, поділись своїм ходом думок

Я б переніс метод `circumference()` з класу `Bicycle` в клас `Wheel`, щоб виклакати цей метод для кожного інстансу `Wheel`.

В нашому прикладі зараз працює так:  `bike1.circumference(bike1.front_wheel)`
Я зробив би так: `bike1.front_wheel.circumference()`

2024-01-18 15:35 UTC, maestro5 commented on app.py
> +    bike1.circumference(bike1.front_wheel)
Мені цікаво чому ти одразу так не зробив?

2024-01-18 15:36 UTC, VodolazUA commented on app.py
> +        return wheel.wheel_diameter * 3.1415
> Погоджуюсь, для бібліотеки замало, але цифра мала бути в константі

Переніс в свою константу. Прибрав імпорт бібліотеки `math`.

2024-01-18 15:37 UTC, VodolazUA commented on app.py
> +    bike1.circumference(bike1.front_wheel)
> Мені цікаво чому ти одразу так не зробив?

Та не знаю. Мені також цікаво. Мабуть втомлений був ))))

2024-01-18 15:49 UTC, maestro5 commented on app.py
> +    bike1.circumference(bike1.front_wheel)
ну це норм.

2024-01-18 15:50 UTC, maestro5 approved these changes

2024-01-19 02:38 UTC, merged